/************************************************************ MEMERR.H
**					   (MemSys - Memory System)
**
**	Name:	MEMERR.H
**	----
**
**	Title:	Memory System Error Codes
**	-----
**
**	Description:
**	-----------
**	This file contains definitions for the MemSys error codes.
**
**	Last Revision:
**	-------------
**	$Revision:	$
**	$Date:	$
**	$Author:	$
**
**	Revision History:
**	----------------
**
**	Rev   Date		By	 Description
**	---   --------	---  -----------
**
**
**	Copyright (C) Momentum Software Corporation, 1989
**
*********************************************************************/

#ifndef MEMERR_H
#define MEMERR_H MEMERR_H

#include "xipcerr.h"

/*********************************************************************
** success return code
*********************************************************************/

#define MEM_SUCCESS 	XIPC_SUCCESS

/*********************************************************************
** XIPC error codes
*********************************************************************/

#define MEM_ER_NOACCESS 		XIPC_ER_NOACCESS
#define MEM_ER_NOTLOGGEDIN		XIPC_ER_NOTLOGGEDIN
#define MEM_ER_CAPACITY 		XIPC_ER_CAPACITY
#define MEM_ER_NOSUBSYSTEM		XIPC_ER_NOSUBSYSTEM		
#define MEM_ER_NOASYNC  		XIPC_ER_NOASYNC
#define MEM_ER_ISFROZEN 		XIPC_ER_ISFROZEN
#define MEM_ER_NOTFROZEN		XIPC_ER_NOTFROZEN
#define MEM_ER_ISMASKED 		XIPC_ER_ISMASKED
#define MEM_ER_NOTMASKED		XIPC_ER_NOTMASKED
#define MEM_ER_BADCONFIGNAME	XIPC_ER_BADCONFIGNAME
#define MEM_ER_BADCONFIGFILE	XIPC_ER_BADCONFIGFILE
#define MEM_ER_BADCONFIGINFO	XIPC_ER_BADCONFIGINFO
#define MEM_ER_BADLISTOFFSET	XIPC_ER_BADLISTOFFSET
#define MEM_ER_BADUSERNAME		XIPC_ER_BADUSERNAME
#define MEM_ER_BADFILENAME		XIPC_ER_BADFILENAME
#define MEM_ER_BADUID			XIPC_ER_BADUID
#define MEM_ER_BADVAL			XIPC_ER_BADVAL
#define MEM_ER_BADOPTION		XIPC_ER_BADOPTION
#define MEM_ER_BADBLOCKOPT		XIPC_ER_BADBLOCKOPT
#define MEM_ER_DUPLICATE		XIPC_ER_DUPLICATE
#define MEM_ER_NOTFOUND 		XIPC_ER_NOTFOUND
#define MEM_ER_NOWAIT			XIPC_ER_NOWAIT
#define MEM_ER_DESTROYED		XIPC_ER_DESTROYED
#define MEM_ER_NOTLOCAL 		XIPC_ER_NOTLOCAL
#define MEM_ER_NOMORE			XIPC_ER_NOMORE
#define MEM_ER_BLOCKCANCELED	XIPC_ER_BLOCKCANCELED
#define MEM_ER_FAILCANWAIT		XIPC_ER_FAILCANWAIT
#define MEM_ER_FAILRESET		XIPC_ER_FAILRESET
#define MEM_ER_FAILACQRESP		XIPC_ER_FAILACQRESP
#define MEM_ER_FAILTIMEOUT		XIPC_ER_FAILTIMEOUT
#define MEM_ER_FAILWAKEUP		XIPC_ER_FAILWAKEUP
#define MEM_ER_BADTRIGGERCODE	XIPC_ER_BADTRIGGERCODE
#define MEM_ER_TRIGGERNOTEXIST	XIPC_ER_TRIGGERNOTEXIST
#define MEM_ER_BADIDENTFILE 	XIPC_ER_BADIDENTFILE
#define MEM_ER_BADTEMPFILE		XIPC_ER_BADTEMPFILE
#define MEM_ER_INSTACTIVE		XIPC_ER_INSTACTIVE
#define MEM_ER_INSTNOTACTIVE	XIPC_ER_INSTNOTACTIVE
#define MEM_ER_ASYNC			XIPC_ER_ASYNC
#define MEM_ER_ASYNCABORT		XIPC_ER_ASYNCABORT
#define MEM_ER_TIMEOUT			XIPC_ER_TIMEOUT
#define MEM_ER_INTERRUPT		XIPC_ER_INTERRUPT
#define MEM_ER_SYSERR			XIPC_ER_SYSERR
#define MEM_ER_FAILCRITON		XIPC_ER_FAILCRITON
#define MEM_ER_FAILCRITOFF		XIPC_ER_FAILCRITOFF
#define MEM_ER_FAILACQTRACESTEP XIPC_ER_FAILACQTRACESTEP
#define MEM_ER_FAILACQTRACEDONE XIPC_ER_FAILACQTRACEDONE
#define MEM_ER_FAILRELTRACESTEP XIPC_ER_FAILRELTRACESTEP
#define MEM_ER_FAILRELTRACEDONE XIPC_ER_FAILRELTRACEDONE
#define MEM_ER_MEMORY			XIPC_ER_MEMORY
#define	MEM_ER_BADBUFFER		XIPC_ER_BADBUFFER

/*********************************************************************
** MemSys error codes
*********************************************************************/

#define MEM_ER_BLOCKEDWRITE (MEM_ER_BASECODE-(XINT)1)
#define MEM_ER_BLOCKEDREAD	(MEM_ER_BASECODE-(XINT)2)
#define MEM_ER_BLOCKEDOWN	(MEM_ER_BASECODE-(XINT)3)
#define MEM_ER_BLOCKEDLOCK	(MEM_ER_BASECODE-(XINT)4)
#define MEM_ER_BADSID		(MEM_ER_BASECODE-(XINT)10)
#define MEM_ER_BADSEGNAME	(MEM_ER_BASECODE-(XINT)11)
#define MEM_ER_BADMID		(MEM_ER_BASECODE-(XINT)12)
#define MEM_ER_BADMIDLIST	(MEM_ER_BASECODE-(XINT)13)
#define MEM_ER_BADTARGET	(MEM_ER_BASECODE-(XINT)14)
#define MEM_ER_BADSIZE		(MEM_ER_BASECODE-(XINT)15)
#define MEM_ER_BADSECTION	(MEM_ER_BASECODE-(XINT)16)
#define MEM_ER_BADTEXT		(MEM_ER_BASECODE-(XINT)17)
#define MEM_ER_BADOWNTYPE	(MEM_ER_BASECODE-(XINT)18)
#define MEM_ER_BADLOCKTYPE	(MEM_ER_BASECODE-(XINT)19)
#define MEM_ER_BADPRIVILEGE (MEM_ER_BASECODE-(XINT)20)
#define MEM_ER_NOTOWNER 	(MEM_ER_BASECODE-(XINT)31)
#define MEM_ER_NOTLOCKED	(MEM_ER_BASECODE-(XINT)32)
#define MEM_ER_MEMBUSY		(MEM_ER_BASECODE-(XINT)33)
#define MEM_ER_ALREADYOWNED (MEM_ER_BASECODE-(XINT)34)
#define MEM_ER_ALREADYLOCKED	(MEM_ER_BASECODE-(XINT)35)
#define MEM_ER_ACCESSDENIED (MEM_ER_BASECODE-(XINT)36)

#define	MEM_ER_CAPACITY_USER	(MEM_ER_BASECODE-(XINT)41)
#define	MEM_ER_CAPACITY_POOL	(MEM_ER_BASECODE-(XINT)42)
#define	MEM_ER_CAPACITY_NODE	(MEM_ER_BASECODE-(XINT)43)
#define	MEM_ER_CAPACITY_SECTION	(MEM_ER_BASECODE-(XINT)44)
#define	MEM_ER_CAPACITY_TABLE	(MEM_ER_BASECODE-(XINT)45)
#define	MEM_ER_CAPACITY_ASYNC_USER	(MEM_ER_BASECODE-(XINT)46)

#define MEM_ER_FAILSTART	(MEM_ER_BASECODE-(XINT)51)
#define MEM_ER_FAILSTOP 	(MEM_ER_BASECODE-(XINT)52)
#define MEM_ER_GHOSTSTART	(MEM_ER_BASECODE-(XINT)53)
#define MEM_ER_GHOSTSTOP	(MEM_ER_BASECODE-(XINT)54)
#define MEM_ER_NOSECCFG 	(MEM_ER_BASECODE-(XINT)55)
#define MEM_ER_NOSECIDS 	(MEM_ER_BASECODE-(XINT)56)

#endif /* MEMERR_H */

/*
** END ****************************************************** MEMERR.H
*/
