/*********************************************************** XIPCERR.H
**		 (XIPC - Extended Interprocess Communications Faclilities)
**
**	Name:	XIPCERR.H
**	----
**
**	Title:	XIPC Error Codes
**	-----
**
**	Description:
**	-----------
**	This file contains definitions for the XIPC error codes.
**
**	Last Revision:
**	-------------
**	$Revision:	$
**	$Date:	$
**	$Author:	$
**
**	Revision History:
**	----------------
**
**	Rev   Date		By	 Description
**	---   --------	---  -----------
**
**
**	Copyright (C) Momentum Software Corporation, 1989
**
*********************************************************************/

#ifndef XIPCERR_H
#define XIPCERR_H XIPCERR_H

/*********************************************************************
** success return code
*********************************************************************/

#define XIPC_SUCCESS	(XINT) (0)
#define XIPC_FAILURE	(XINT) (-1)

/*********************************************************************
** base codes
*********************************************************************/

#define XIPC_ER_BASECODE		(XINT)(-1000)
#define SEM_ER_BASECODE 		(XINT)(-1300)
#define QUE_ER_BASECODE 		(XINT)(-1600)
#define MEM_ER_BASECODE 		(XINT)(-1900)
#define MOM_ER_BASECODE 		(XINT)(-2500)

/*********************************************************************
** error codes
*********************************************************************/

#define XIPC_ER_NOACCESS			(XIPC_ER_BASECODE-(XINT)1)
#define XIPC_ER_NOTLOGGEDIN 		(XIPC_ER_BASECODE-(XINT)2)
#define XIPC_ER_NOSUBSYSTEM 		(XIPC_ER_BASECODE-(XINT)4)
#define XIPC_ER_INSTNOTFOUND		(XIPC_ER_BASECODE-(XINT)5)
#define XIPC_ER_NOASYNC 			(XIPC_ER_BASECODE-(XINT)6)
#define XIPC_ER_ISFROZEN			(XIPC_ER_BASECODE-(XINT)7)
#define XIPC_ER_NOTFROZEN			(XIPC_ER_BASECODE-(XINT)8)
#define XIPC_ER_ISMASKED			(XIPC_ER_BASECODE-(XINT)9)
#define XIPC_ER_NOTMASKED			(XIPC_ER_BASECODE-(XINT)10)
#define XIPC_ER_BADCONFIGNAME		(XIPC_ER_BASECODE-(XINT)11)
#define XIPC_ER_BADINSTNAME 		(XIPC_ER_BASECODE-(XINT)11)
#define XIPC_ER_BADCONFIGFILE		(XIPC_ER_BASECODE-(XINT)12)
#define XIPC_ER_BADCONFIGINFO		(XIPC_ER_BASECODE-(XINT)13)
#define XIPC_ER_BADLISTOFFSET		(XIPC_ER_BASECODE-(XINT)14)
#define XIPC_ER_NOTCONNECTED		(XIPC_ER_BASECODE-(XINT)15)
#define XIPC_ER_LOGINNOTFOUND		(XIPC_ER_BASECODE-(XINT)16)
#define XIPC_ER_AMBIGUOUS			(XIPC_ER_BASECODE-(XINT)17)
#define XIPC_ER_BUSY				(XIPC_ER_BASECODE-(XINT)18)
#define XIPC_ER_BADBUFFER			(XIPC_ER_BASECODE-(XINT)19)
#define XIPC_ER_FILEOPEN			(XIPC_ER_BASECODE-(XINT)20)
#define XIPC_ER_BADUSERNAME 		(XIPC_ER_BASECODE-(XINT)21)
#define XIPC_ER_BADFILENAME 		(XIPC_ER_BASECODE-(XINT)22)
#define XIPC_ER_BADUID				(XIPC_ER_BASECODE-(XINT)23)
#define XIPC_ER_BADVAL				(XIPC_ER_BASECODE-(XINT)24)
#define XIPC_ER_BADIDENTFILE		(XIPC_ER_BASECODE-(XINT)25)
#define XIPC_ER_BADTEMPFILE 		(XIPC_ER_BASECODE-(XINT)26)
#define XIPC_ER_NOROOTDIR			(XIPC_ER_BASECODE-(XINT)27)
#define XIPC_ER_BADOPTION			(XIPC_ER_BASECODE-(XINT)30)
#define XIPC_ER_BADBLOCKOPT 		(XIPC_ER_BASECODE-(XINT)31)
#define XIPC_ER_DUPLICATE			(XIPC_ER_BASECODE-(XINT)32)
#define XIPC_ER_NOTFOUND			(XIPC_ER_BASECODE-(XINT)33)
#define XIPC_ER_NOWAIT				(XIPC_ER_BASECODE-(XINT)34)
#define XIPC_ER_DESTROYED			(XIPC_ER_BASECODE-(XINT)35)
#define XIPC_ER_BLOCKCANCELED		(XIPC_ER_BASECODE-(XINT)36)
#define XIPC_ER_NOTLOCAL			(XIPC_ER_BASECODE-(XINT)37)
#define XIPC_ER_NOMORE				(XIPC_ER_BASECODE-(XINT)38)
#define XIPC_ER_NOTSUPPORTED		(XIPC_ER_BASECODE-(XINT)40)
#define XIPC_ER_FAILCANWAIT 		(XIPC_ER_BASECODE-(XINT)41)
#define XIPC_ER_FAILRESET			(XIPC_ER_BASECODE-(XINT)42)
#define XIPC_ER_FAILACQRESP 		(XIPC_ER_BASECODE-(XINT)43)
#define XIPC_ER_FAILTIMEOUT 		(XIPC_ER_BASECODE-(XINT)44)
#define XIPC_ER_FAILWAKEUP			(XIPC_ER_BASECODE-(XINT)45)
#define XIPC_ER_BADTRIGGERCODE		(XIPC_ER_BASECODE-(XINT)51)
#define XIPC_ER_TRIGGERNOTEXIST 	(XIPC_ER_BASECODE-(XINT)52)
#define XIPC_ER_ALREADY_OWNED		(XIPC_ER_BASECODE-(XINT)55)
#define XIPC_ER_NOTOWNER			(XIPC_ER_BASECODE-(XINT)56)
#define XIPC_ER_NOTOWNED			(XIPC_ER_BASECODE-(XINT)57)
#define XIPC_ER_FAILSTART			(XIPC_ER_BASECODE-(XINT)61)
#define XIPC_ER_INSTACTIVE			(XIPC_ER_BASECODE-(XINT)81)
#define XIPC_ER_INSTNOTACTIVE		(XIPC_ER_BASECODE-(XINT)82)
#define XIPC_ER_INSTFAILREG 		(XIPC_ER_BASECODE-(XINT)83)
#define XIPC_ER_GHOSTSTART			(XIPC_ER_BASECODE-(XINT)84)
#define XIPC_ER_GHOSTSTOP			(XIPC_ER_BASECODE-(XINT)85)
#define XIPC_ER_DUPINSTANCE 		(XIPC_ER_BASECODE-(XINT)86)
#define XIPC_ER_NOPLATFORMFILE		(XIPC_ER_BASECODE-(XINT)88)
#define XIPC_ER_PLATNOTACTIVE		(XIPC_ER_BASECODE-(XINT)89)
#define XIPC_ER_ASYNC				(XIPC_ER_BASECODE-(XINT)97)
#define XIPC_ER_ASYNCABORT			(XIPC_ER_BASECODE-(XINT)98)
#define XIPC_ER_TIMEOUT 			(XIPC_ER_BASECODE-(XINT)99)
#define XIPC_ER_INTERRUPT			(XIPC_ER_BASECODE-(XINT)100)
#define XIPC_ER_SYSERR				(XIPC_ER_BASECODE-(XINT)101)
#define XIPC_ER_FAILCRITON			(XIPC_ER_BASECODE-(XINT)102)
#define XIPC_ER_FAILCRITOFF 		(XIPC_ER_BASECODE-(XINT)103)
#define XIPC_ER_CAPACITY_NAMESPACE	(XIPC_ER_BASECODE-(XINT)105)
#define XIPC_ER_CAPACITY_NODE		(XIPC_ER_BASECODE-(XINT)106)
#define XIPC_ER_CAPACITY_APPQUEUE	(XIPC_ER_BASECODE-(XINT)107)
#define XIPC_ER_CAPACITY_INSTANCE	(XIPC_ER_BASECODE-(XINT)108)
#define XIPC_ER_FAILACQTRACESTEP	(XIPC_ER_BASECODE-(XINT)111)
#define XIPC_ER_FAILACQTRACEDONE	(XIPC_ER_BASECODE-(XINT)112)
#define XIPC_ER_FAILRELTRACESTEP	(XIPC_ER_BASECODE-(XINT)113)
#define XIPC_ER_FAILRELTRACEDONE	(XIPC_ER_BASECODE-(XINT)114)
#define XIPC_ER_FATAL				(XIPC_ER_BASECODE-(XINT)115)
#define XIPC_ER_CAPACITY_THREAD 	(XIPC_ER_BASECODE-(XINT)116)
#define XIPC_ER_LOGGEDIN			(XIPC_ER_BASECODE-(XINT)117)
#define XIPC_ER_OPTIONALREADYSET	(XIPC_ER_BASECODE-(XINT)120)
#define XIPC_ER_MEMORY				(XIPC_ER_BASECODE-(XINT)121)
#define XIPC_ER_INPROGRESS			(XIPC_ER_BASECODE-(XINT)122)
#define XIPC_ER_ASYNCCOMPLETED		(XIPC_ER_BASECODE-(XINT)123)
#define XIPC_ER_INVALIDSETOPTION	(XIPC_ER_BASECODE-(XINT)124)
#define XIPC_ER_OPTIONNOTSET		(XIPC_ER_BASECODE-(XINT)125)
#define XIPC_ER_INVALIDNAMESPACE	(XIPC_ER_BASECODE-(XINT)126)
#define XIPC_ER_IDLD				(XIPC_ER_BASECODE-(XINT)127)

#define  XIPC_CAPACITY_THREAD			XIPC_XIPC_CAPACITY

#endif /* XIPCERR_H */

/*
** END ***************************************************** XIPCERR.H
*/
